In [2]:
import torch


# 텐서의 조작(Manipulations)
인덱싱(Indexing) : NumPy처럼 인덱싱 형태로 사용가능

In [3]:

x = torch.Tensor([[1,2],
                [3,4]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:,0])
print(x[:,1])

print(x[0,:])
print(x[1,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


view : 텐서의 크기(size)나 모양(shape)을 변경
*   기본적으로 변경 전과 후에 텐서 안의 원소 객수가 유지 되어야함
*   -1로 설정되면 계산을 통해 해당 크기 값을 유추



In [4]:
#view라는 메소드를 사용
#view는 torch에서만 사용 가능하다.
x =torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5,-1) # -1 : 나머지는 네가 알아서 자동으로 계산해줘
print(z)


tensor([[ 1.1668,  0.6823, -0.4378, -0.0294,  1.1203],
        [-0.4748, -0.0532,  0.3817, -0.0447, -0.1955],
        [-1.4492, -0.8696,  0.2968,  1.7203,  1.4841],
        [ 0.2385, -0.4685,  0.2204,  0.4249, -0.4447]])
tensor([ 1.1668,  0.6823, -0.4378, -0.0294,  1.1203, -0.4748, -0.0532,  0.3817,
        -0.0447, -0.1955, -1.4492, -0.8696,  0.2968,  1.7203,  1.4841,  0.2385,
        -0.4685,  0.2204,  0.4249, -0.4447])
tensor([[ 1.1668,  0.6823, -0.4378, -0.0294],
        [ 1.1203, -0.4748, -0.0532,  0.3817],
        [-0.0447, -0.1955, -1.4492, -0.8696],
        [ 0.2968,  1.7203,  1.4841,  0.2385],
        [-0.4685,  0.2204,  0.4249, -0.4447]])


item : 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음

In [5]:
x = torch.randn(1)
print(x)
print(x.dtype)
print(x.item())
print(x.dtype)


tensor([0.0572])
torch.float32
0.057224828749895096
torch.float32


스칼라값이 하나만 존재해야 item() 사용가능
아니면 에러난다.

In [7]:
x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.5079, -0.8438])


RuntimeError: ignored

squeeze : 차원 축소(제거)

In [8]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.9655, 0.5569, 0.4518],
         [0.6196, 0.5832, 0.6650],
         [0.3645, 0.7318, 0.2882]]])
torch.Size([1, 3, 3])


In [9]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.9655, 0.5569, 0.4518],
        [0.6196, 0.5832, 0.6650],
        [0.3645, 0.7318, 0.2882]])
torch.Size([3, 3])


unsqueeze : 차원 증가(생성)

In [10]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.2841, 0.5894, 0.4663],
        [0.4565, 0.0524, 0.5947],
        [0.0931, 0.3371, 0.9601]])
torch.Size([3, 3])


In [13]:
tensor = t.unsqueeze(dim=0) # 0번째 차원을 기준으로 늘려줘
print(tensor)
print(tensor.shape)

tensor([[[0.2841, 0.5894, 0.4663],
         [0.4565, 0.0524, 0.5947],
         [0.0931, 0.3371, 0.9601]]])
torch.Size([1, 3, 3])


In [14]:
tensor = t.unsqueeze(dim=2) # 2번째 차원을 기준으로 늘려줘
print(tensor)
print(tensor.shape)

tensor([[[0.2841],
         [0.5894],
         [0.4663]],

        [[0.4565],
         [0.0524],
         [0.5947]],

        [[0.0931],
         [0.3371],
         [0.9601]]])
torch.Size([3, 3, 1])
