In [3]:
!pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116


ERROR: unknown command "unintstall" - maybe you meant "uninstall"
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 GB 481.8 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 32.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 55.3 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1+cu118
    Uninstalling torch-2.0.1+cu118:
      Successfully uninstalled torch-2.0.1+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.2+cu118
    Uninstalling torchvision-0.15.2+cu118:
      Successfully uninstalled torchvision-0.15.2+cu118
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.0.2+cu118
    Uninstalling torchaudio-2.0.2+cu118:
      Successfully uninstalled torchaudio-2.0.2+cu118
ERROR: pip's dependency resolver does not currently take into acc

초기화 되지 않은 텐서

In [6]:
import torch
torch.__version__

x=torch.empty(4,2)
print(x)
# 비어서 초기화 하지 않은값
# 실행할때마다 다른 초기화되지 않은 값들이 나온다.
# 우리가 초기화하지 않아서 기준없는 랜덤한 값이 텐서에 있음

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [3.5311e-31, 3.3082e-41],
        [3.4916e-32, 3.3082e-41]])


무작위로 초기화된 텐서

In [10]:
x = torch.rand(4,2)
# rand - 랜덤의 줄임
print(x)
# 초기화는 되었는데 랜덤을 기준으로 초기화됌

tensor([[0.9296, 0.7218],
        [0.1225, 0.2466],
        [0.9804, 0.3434],
        [0.3951, 0.3707]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [11]:
x = torch.zeros(4,2)
x_long = torch.zeros(4,2,dtype=torch.long)
# long타입이란 정수 데이터 타입 중 하나로서, 64비트 정수를 표현하는 데 사용됩니다
# 정수 라벨(label) 데이터를 다룰 때 주로 사용되며, 예를 들어 분류 모델의 타겟 라벨 데이터를 표현하는 데 사용됩니다.
# 이는 모델의 출력과 실제 라벨 간의 비교 및 평가에 활용됩니다.
print(f'x:{x}')
print(f'x_long :{x_long}')

x:tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
x_long :tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [12]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


2x4크기, double 타입, 1로 채워진 텐서

In [15]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


x와 같은 크기, float 타입, 무작위로 채워진 텐서


In [18]:
x = torch.randn_like(x,dtype=torch.float)
print(x)
# x = torch.randn_like(작성된변수,dtype=torch.float)
# 작성된 변수 자리에 작성된 변수의 텐서 크기를 가짐
# 위에 기존 x는 (2,4)텐서로 데이터 타입은 float로 해줘

tensor([[ 0.2088,  0.8688,  0.5087,  1.2780],
        [ 0.9449, -0.3538, -0.2669, -0.5023]])


텐서의 크기 계산

In [19]:
print(x.size())

torch.Size([2, 4])
