# 텐서의 연산(Operations)
*   텐서에 대한 수학연산, 삼각함수, 비트연산, 집계



In [2]:
import math
import torch
a=torch.rand(1,2)
print(a) # tensor([[0.5143, 0.1689]])
a=torch.rand(1,2)*2 -1
print(a) # tensor([[0.0686, 0.0326]])
a=a*2 -1
print(a) # tensor([[-0.8627, -0.9348]])
print(torch.abs(a))  # tensor([[0.8627, 0.9348]]) # 절대값
print(torch.ceil(a)) # tensor([[-0., -0.]])       # 올림한 값
print(torch.floor(a)) # tensor([[-1., -1.]])      #  내림한 값
print(torch.clamp(a,-0.5,0.5)) # tensor([[-0.5000, -0.5000]])
# clamp는 최소 -0.5에서 0.5 사이 값으로 만들어줌
# 최대 값을 넘으면 최대값으로 최소값을 넘으면 최소값으로
# 한정적으로 만들어줌

tensor([[0.7399, 0.8843]])
tensor([[-0.2319,  0.2361]])
tensor([[-1.4638, -0.5277]])
tensor([[1.4638, 0.5277]])
tensor([[-1., -0.]])
tensor([[-2., -1.]])
tensor([[-0.5000, -0.5000]])


In [3]:
print(a)
print(torch.min(a)) #최소값
print(torch.max(a)) # 최대값
print(torch.mean(a)) # 평균값
print(torch.std(a)) # 표준 편차
print(torch.prod(a)) # a의 모든 원소를 곱한 결과를 반환하는 함수
print(torch.unique(torch.tensor([1,2,4,1,2,3])))
'''
torch.unique() 함수는 주어진 텐서의 고유한(unique) 원소들을 반환하는 함수입니다.
중복되지 않은 원소들만 반환되며, 원소들은 반환되는 순서대로 고유성이 보장됩니다.
주어진 입력 텐서 [1,2,4,1,2,3]에 대해 torch.unique() 함수를 사용하면 중복을 제거한 고유한 원소들이 반환됩니다.
결과는 오름차순으로 정렬되어 나타납니다. 따라서 출력은 [1, 2, 3, 4]가 될 것입니다.
'''

tensor([[-1.4638, -0.5277]])
tensor(-1.4638)
tensor(-0.5277)
tensor(-0.9958)
tensor(0.6619)
tensor(0.7725)
tensor([1, 2, 3, 4])


'\ntorch.unique() 함수는 주어진 텐서의 고유한(unique) 원소들을 반환하는 함수입니다. \n중복되지 않은 원소들만 반환되며, 원소들은 반환되는 순서대로 고유성이 보장됩니다.\n주어진 입력 텐서 [1,2,4,1,2,3]에 대해 torch.unique() 함수를 사용하면 중복을 제거한 고유한 원소들이 반환됩니다.\n결과는 오름차순으로 정렬되어 나타납니다. 따라서 출력은 [1, 2, 3, 4]가 될 것입니다.\n'

max와 min은 dim인자를 줄 경우 argmax와 argmin도 함께 리턴
*   argmax : 최대값을 가진 인덱스
*   argmin : 최소값을 가진 인덱스



In [4]:
x = torch.rand(2,3)
print(x)
print(x.max(dim=0))
print(x.max(dim=1)) # dim =1이란 열 기준
'''
요약하면, 제공한 코드는 torch.max 함수를 사용하여
텐서의 특정 차원을 따라 최대값과 해당 인덱스를 찾는 방법을 보여줍니다.
첫 번째 호출은 두 번째 차원을 따라 최대값을 찾고,
 두 번째 호출은 첫 번째 차원을 따라 최대값을 찾습니다.
 (2,3) 이니까 앞에서 1원 0차원 순서로
 '''

tensor([[0.0928, 0.5799, 0.8275],
        [0.7723, 0.6789, 0.0919]])
torch.return_types.max(
values=tensor([0.7723, 0.6789, 0.8275]),
indices=tensor([1, 1, 0]))
torch.return_types.max(
values=tensor([0.8275, 0.7723]),
indices=tensor([2, 0]))


'\n요약하면, 제공한 코드는 torch.max 함수를 사용하여 \n텐서의 특정 차원을 따라 최대값과 해당 인덱스를 찾는 방법을 보여줍니다.\n첫 번째 호출은 두 번째 차원을 따라 최대값을 찾고,\n 두 번째 호출은 첫 번째 차원을 따라 최대값을 찾습니다.\n (2,3) 이니까 앞에서 1원 0차원 순서로 \n '

In [5]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.0928, 0.5799, 0.8275],
        [0.7723, 0.6789, 0.0919]])
torch.return_types.min(
values=tensor([0.0928, 0.5799, 0.0919]),
indices=tensor([0, 0, 1]))
torch.return_types.min(
values=tensor([0.0928, 0.0919]),
indices=tensor([0, 2]))


torch.add : 덧셈


In [6]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
z = x+y
print(z)
result =torch.empty(2,4)
torch.add(x,y,out=result) # result에 결과를 저장해줘
print('result : ',result)

tensor([[0.6467, 0.3239],
        [0.9038, 0.8565]])
tensor([[0.2410, 0.5853],
        [0.3928, 0.4548]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])
result :  tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])


<ipython-input-6-34fca5797a18>:8: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  torch.add(x,y,out=result) # result에 결과를 저장해줘


in-place 방식


*   in-place방식으로 텐서의 값을 변경하는 연산 뒤에 '_'가 붙음
*   x.copy(y), x.t_()



In [7]:
# 한 마디로 복사하는 것임
print(x)
print(y)
y.add_(x) # y에 x를 더한 결과를 y에 저장 (in-place 연산)
print(y)


tensor([[0.6467, 0.3239],
        [0.9038, 0.8565]])
tensor([[0.2410, 0.5853],
        [0.3928, 0.4548]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])


torch.sub : 뺄샘

In [8]:
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))
print(x.sub_(y))

tensor([[0.6467, 0.3239],
        [0.9038, 0.8565]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])


torch.mul : 곱셈

In [9]:
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))
print(x.mul_(y))

tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])
tensor([[-0.2140, -0.5322],
        [-0.5093, -0.5963]])
tensor([[-0.2140, -0.5322],
        [-0.5093, -0.5963]])
tensor([[-0.2140, -0.5322],
        [-0.5093, -0.5963]])
tensor([[-0.2140, -0.5322],
        [-0.5093, -0.5963]])


torch.div : 나눗셈

In [10]:
print(x)
print(y)
print(x/y)
print(torch.div(x,y))
print(x.div(y))
print(x.div_(y))

tensor([[-0.2140, -0.5322],
        [-0.5093, -0.5963]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])


torch.mm: 내적 (dot product)

In [12]:
print(x)
print(y)
print(torch.matmul(x,y)) # 행렬 곱
z =torch.mm(x,y) # mm으로 죽열서 사용가능
print(z)
print(torch.svd(z)) # 행렬값을 u,s,v로 분해처럼 분해가능

tensor([[-0.2410, -0.5853],
        [-0.3928, -0.4548]])
tensor([[0.8877, 0.9092],
        [1.2966, 1.3112]])
tensor([[-0.9729, -0.9867],
        [-0.9384, -0.9535]])
tensor([[-0.9729, -0.9867],
        [-0.9384, -0.9535]])
torch.return_types.svd(
U=tensor([[-0.7194, -0.6946],
        [-0.6946,  0.7194]]),
S=tensor([1.9261e+00, 9.3101e-04]),
V=tensor([[ 0.7018,  0.7124],
        [ 0.7124, -0.7018]]))
