torch <-> numpy


*   Torch Tensor(텐서)를 NumPy array(배열)로 변환 가능
> -   numpy()
> -   from_numpy()
*   Tensor가 CPU상에 있다면 NumPY 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함



In [2]:
import torch
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [6]:
b = a.numpy()
print(b) # tensor가 사라지고 넘파이 형태(배열)로 나타난다.

[1. 1. 1. 1. 1. 1. 1.]
float32


In [10]:
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4. 4. 4.]


In [13]:
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a) # numpy -> tensor
print(a)
print(b)
np.add(a,1,out=a) # torch랑 넘파이랑 메모리를 공유한다. # cpu의 경우에만 해당되며 gpu는 서로 메모리가 달라서 안되는거같다.
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
