stack : 텐서간 결합

In [3]:
import torch
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)

print(torch.stack([x,y,z])) # 텐서간의 결합

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


cat : 텐서를 결합하는 메소드(concatenate)
*   넘파이의 stack과 유사하지만 쌓을 dim이 존재해야함
*   해당 차원을 늘려준 후 결합



In [4]:
# 디멘션으로 해당 차원을 늘려준다음에 해당 차원을 늘려준 후 결합
a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)
c = torch.cat((a,b),dim=0) # a,b를 concatenate해줘, 디멘션은 0 차원 기준
print(c)
print(c.shape)

tensor([[[ 0.1673, -1.8906, -0.9735],
         [ 0.1240,  1.6538, -0.1694],
         [ 0.8256, -0.5530,  0.6743]]])
tensor([[[ 0.2411, -2.1453, -0.1905],
         [ 0.3072, -0.0225, -0.2727],
         [-0.3366, -0.7088,  1.1637]]])
tensor([[[ 0.1673, -1.8906, -0.9735],
         [ 0.1240,  1.6538, -0.1694],
         [ 0.8256, -0.5530,  0.6743]],

        [[ 0.2411, -2.1453, -0.1905],
         [ 0.3072, -0.0225, -0.2727],
         [-0.3366, -0.7088,  1.1637]]])
torch.Size([2, 3, 3])


In [5]:
c = torch.cat((a,b),dim=1) # 디멘션은 1차원 기준
print(c)
print(c.shape) # c.shape = c.size()

tensor([[[ 0.1673, -1.8906, -0.9735],
         [ 0.1240,  1.6538, -0.1694],
         [ 0.8256, -0.5530,  0.6743],
         [ 0.2411, -2.1453, -0.1905],
         [ 0.3072, -0.0225, -0.2727],
         [-0.3366, -0.7088,  1.1637]]])
torch.Size([1, 6, 3])


In [6]:
c = torch.cat((a,b),dim=2) # 디멘션은 2차원 기준
print(c)
print(c.shape) # c.shape = c.size()

tensor([[[ 0.1673, -1.8906, -0.9735,  0.2411, -2.1453, -0.1905],
         [ 0.1240,  1.6538, -0.1694,  0.3072, -0.0225, -0.2727],
         [ 0.8256, -0.5530,  0.6743, -0.3366, -0.7088,  1.1637]]])
torch.Size([1, 3, 6])


chunk : 텐서를 여러 개로 나눌 때 사용(몇 개로 나눌 것인가?)

In [10]:
tensor = torch.rand(3,6)
print(tensor)
t1,t2,t3 = torch.chunk(tensor,3,dim=1) # 변수 tensor를 3개로 나눠줘. 기준은 1번째 차원이야
print(t1)
print(t2)
print(t3)
'''
tensor([[0.8722, 0.7617, / 0.4365, 0.2774, / 0.6725, 0.1190],
        [0.0339, 0.1010, / 0.6085, 0.5499, / 0.7500, 0.9729],
        [0.4590, 0.4374, / 0.8977, 0.6290, / 0.2681, 0.0691]])
        2개 단위로 해서 3개로 나눠줌
tensor([[0.8722, 0.7617],
        [0.0339, 0.1010],
        [0.4590, 0.4374]])
tensor([[0.4365, 0.2774],
        [0.6085, 0.5499],
        [0.8977, 0.6290]])
tensor([[0.6725, 0.1190],
        [0.7500, 0.9729],
        [0.2681, 0.0691]])
'''


tensor([[0.2330, 0.7696, 0.6933, 0.7004, 0.8159, 0.7537],
        [0.4638, 0.0057, 0.7510, 0.8732, 0.0358, 0.2490],
        [0.0797, 0.0212, 0.9815, 0.7622, 0.8219, 0.9210]])
tensor([[0.2330, 0.7696],
        [0.4638, 0.0057],
        [0.0797, 0.0212]])
tensor([[0.6933, 0.7004],
        [0.7510, 0.8732],
        [0.9815, 0.7622]])
tensor([[0.8159, 0.7537],
        [0.0358, 0.2490],
        [0.8219, 0.9210]])


'\ntensor([[0.8722, 0.7617, / 0.4365, 0.2774, / 0.6725, 0.1190],\n        [0.0339, 0.1010, / 0.6085, 0.5499, / 0.7500, 0.9729],\n        [0.4590, 0.4374, / 0.8977, 0.6290, / 0.2681, 0.0691]])\n        2개 단위로 해서 3개로 나눠줌\ntensor([[0.8722, 0.7617],\n        [0.0339, 0.1010],\n        [0.4590, 0.4374]])\ntensor([[0.4365, 0.2774],\n        [0.6085, 0.5499],\n        [0.8977, 0.6290]])\ntensor([[0.6725, 0.1190],\n        [0.7500, 0.9729],\n        [0.2681, 0.0691]])\n'

split : chunck와 동일한 기능이지만 조금 다름 (텐서의 크기는 몇인가?)

In [8]:
# 나눌 때 어떤 방식으로 나누는가의 차이
tensor = torch.rand(3,6)
t1,t2 = torch.split(tensor,3,dim=1) # 변수 tensor의 크기가 몇인지 지정하는 것
# 청크와 스플릿이 동일한 인자인데도 나누는 방법이 다르다
print(tensor)
print(t1)
print(t2)

tensor([[0.7847, 0.3454, 0.7728, 0.1853, 0.2052, 0.3158],
        [0.9513, 0.9022, 0.1141, 0.8109, 0.3637, 0.2243],
        [0.2328, 0.6953, 0.9126, 0.2111, 0.6650, 0.2681]])
tensor([[0.7847, 0.3454, 0.7728],
        [0.9513, 0.9022, 0.1141],
        [0.2328, 0.6953, 0.9126]])
tensor([[0.1853, 0.2052, 0.3158],
        [0.8109, 0.3637, 0.2243],
        [0.2111, 0.6650, 0.2681]])
